name: Update Package Cache

on:
  release:
    types: [published]

jobs:
  cache_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Update Cache
        run:  GOPROXY=proxy.golang.org go list -m github.com/peterHoburg/aws-sdk-go-v2-sso-login@${{ env.RELEASE_VERSION }}
